/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */
package org.catrobat.catroid.wrapper;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int OP = 6;
  /** RegularExpression Id. */
  int FU = 7;
  /** RegularExpression Id. */
  int CONST = 8;
  /** RegularExpression Id. */
  int SENSOR = 9;
  /** RegularExpression Id. */
  int VAR = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUM>",
    "<OP>",
    "<FU>",
    "<CONST>",
    "<SENSOR>",
    "<VAR>",
    "\"\\\'\"",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
